"""Conservative parser-artifact cleanup stage."""

from __future__ import annotations

import re

from lexrag.ingestion.normalizer.base_normalizer import BaseNormalizer
from lexrag.ingestion.parser.schemas.parsed_block import ParsedBlock

_PAGE_NUMBER_LINE = re.compile(r"^\s*page\s+\d+(\s+of\s+\d+)?\s*$", re.IGNORECASE)
_GENERATED_EXPORT = re.compile(
    r"^\s*(generated by|exported by|printed from)\b.*$",
    re.IGNORECASE,
)
_CONFIDENTIAL_BANNER = re.compile(
    r"^\s*(confidential|private and confidential|internal use only)\s*$",
    re.IGNORECASE,
)
_SCANNER_NOISE = re.compile(r"^[\W_]{6,}$")


class ParserArtifactCleaner(BaseNormalizer):
    """Removes high-confidence parser artifacts and leaves domain text intact.

    The stage explicitly avoids aggressive repetition cleanup because legal and
    regulatory corpora often repeat intentionally meaningful clauses.
    """

    def normalize(self, block: ParsedBlock) -> ParsedBlock:
        """Drops obvious parser noise using document-type-aware heuristics.

        Args:
            block: Parsed block candidate.

        Returns:
            Updated block with artifact lines removed when they are clearly
            non-semantic extraction noise.
        """
        if self._is_protected(block):
            return block
        text = block.text or ""
        if not text.strip():
            return block
        cleaned_lines = self._collect_semantic_lines(block=block, text=text)
        metadata = dict(block.metadata)
        metadata["artifact_cleanup_removed_lines"] = len(text.splitlines()) - len(
            cleaned_lines
        )
        return block.model_copy(
            update={"text": "\n".join(cleaned_lines).strip(), "metadata": metadata}
        )

    def _collect_semantic_lines(self, *, block: ParsedBlock, text: str) -> list[str]:
        cleaned_lines: list[str] = []
        for line in text.splitlines():
            stripped_line = line.strip()
            if not stripped_line:
                continue
            if self._is_artifact(block=block, line=stripped_line):
                continue
            cleaned_lines.append(stripped_line)
        return cleaned_lines

    def _is_artifact(self, *, block: ParsedBlock, line: str) -> bool:
        if _PAGE_NUMBER_LINE.search(line) or _GENERATED_EXPORT.search(line):
            return True
        if _SCANNER_NOISE.search(line):
            return True
        if self._is_legal_sensitive_document(block):
            return False
        return bool(_CONFIDENTIAL_BANNER.search(line))

    def _is_legal_sensitive_document(self, block: ParsedBlock) -> bool:
        doc_type = (block.doc_type or "").strip().lower()
        return doc_type in self.config.legal_sensitive_document_types

    def _is_protected(self, block: ParsedBlock) -> bool:
        return block.block_type in self.config.protected_block_types
